In [ ]:
# NUMPY - Biblioteca matemática, mais utilizada com álgebra linear. Vetores e Matrizes

In [1]:
# Importando a biblioteca NumPy

import numpy

# Estruturas Unidimensionais

In [2]:
a1 = numpy.array(['Spark', 'Hadoop', 'R', 'Python', 'SQL', 'C#'])

In [3]:
a1

array(['Spark', 'Hadoop', 'R', 'Python', 'SQL', 'C#'],
      dtype='<U6')

In [ ]:
# Arrays podem contér listas de tipos diferentes

# Estruturas Bidimensionais

In [4]:
a2 = numpy.array([ ['Altura', 'Largura', 'Profundidade'], [40, 88, 15] ])

In [5]:
a2

array([['Altura', 'Largura', 'Profundidade'],
       ['40', '88', '15']],
      dtype='<U12')

In [6]:
a3 = numpy.array([ [10, 13, 20], [20, 13, 10], [13, 20, 10] ])

In [7]:
a3

array([[10, 13, 20],
       [20, 13, 10]])

In [9]:
a4 = numpy.array([ [10, 13, 20], [20, 13, 10], [13, 20, 10] ])

In [10]:
a4

array([[10, 13, 20],
       [20, 13, 10],
       [13, 20, 10]])

In [11]:
# Tamanho do Array

print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a4.shape)

(6,)
(2, 3)
(2, 3)
(3, 3)


In [12]:
# Dimensões do Array

a1.ndim

1

In [13]:
a2.ndim

2

In [14]:
a4.ndim

2

# Ausência ou Presença de parenteses
# Podemos realizar uma analogia com características e ações. O uso de parênteses reflete uma AÇÃO, ausência reflete uma CARACTERÍSTICA.

In [15]:
# O método max() não funciona em array de tipo heterogêneo

a3.max()

20

In [16]:
# Atributo 

a4.ndim

2

# Método ARANGE

In [17]:
array = numpy.arange(10)

array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Usando Stard / End - de 0 - 100 de 10 em 10

array = numpy.arange(1, 100, 10)

In [19]:
array

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

# Criando estruturas de dados com LINSPACE

In [20]:
#  A diferença do LINSPACE para o ARANGE é que no ARANGE o último argumento é o incremento, e no LINSPACE o último argumento é o número de elementos do vetor (aleatório)

matriz = numpy.linspace(2, 15, 20)

matriz

array([  2.        ,   2.68421053,   3.36842105,   4.05263158,
         4.73684211,   5.42105263,   6.10526316,   6.78947368,
         7.47368421,   8.15789474,   8.84210526,   9.52631579,
        10.21052632,  10.89473684,  11.57894737,  12.26315789,
        12.94736842,  13.63157895,  14.31578947,  15.        ])

In [21]:
matriz = numpy.linspace(0, 10, 5)

matriz

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [22]:
matriz = numpy.linspace(0, 5, 5)

matriz

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ])

# Estrutura de matrizes

In [23]:
# Numpy.Zeros

matriz = numpy.zeros((10, 10))

matriz

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [24]:
# Numpy.Ones

matriz = numpy.ones((2, 3))

matriz

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [25]:
# Numpy.Eye - Produz uma matriz do tipo Identity

matriz = numpy.eye(10)

matriz

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [26]:
# Numpy.Diag - Produz o mesmo resultado, porém, pode-se definir os números da diagonal

matriz = numpy.diag((1, 3, 5, 7, 9, 11, 13, 15, 17, 19))

matriz

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  5,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  9,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 13,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 15,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 17,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 19]])

In [31]:
# Numpy.Empty - Produz uma matriz vazia

matriz = numpy.empty((10, 5))

matriz

array([[              nan,   9.88131292e-324,   2.76676762e-321,
          1.97626258e-323,   6.36356552e-321],
       [  1.97626258e-323,   6.08688876e-321,   2.03060980e-321,
          4.03157567e-321,   2.03060980e-321],
       [  3.73513628e-321,   2.03060980e-321,   2.23317672e-321,
          2.03060980e-321,   3.99205042e-321],
       [  2.03060980e-321,   2.76676762e-321,   2.03060980e-321,
          5.35567160e-321,   2.03060980e-321],
       [  6.36356552e-321,   2.03060980e-321,   3.55727265e-321,
          2.03060980e-321,   2.76676762e-321],
       [  1.97626258e-323,   6.36356552e-321,   1.97626258e-323,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000

In [32]:
# Numpy.Tile - Multiplica os ARRAYS

matriz = numpy.tile(numpy.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]), 3 )

In [33]:
matriz

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [34]:
matriz = numpy.tile(numpy.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]), (3,6) ) # Número de vezes do ARRAY na vertical e horizontal

matriz

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9],
       [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9],
       [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9]])