In [2]:
# Importação do NUMPY

import numpy

# Tipagem de DADOS

In [3]:
# Podemos passar um tipo para o ARRAY por parâmetro

a = numpy.array([-10, 10, 30, 45, 75, 89], dtype = 'float')

In [4]:
a

array([-10.,  10.,  30.,  45.,  75.,  89.])

In [5]:
# A propriedade dtype retorna o tipo de elementos do ARRAY

a.dtype

dtype('float64')

In [6]:
# Caso não passe o tipo para o Python, ele definirá automaticamente

b = numpy.array([0, 12, -43, 77, 90, -20])

b.dtype

dtype('int32')

In [7]:
# Caso exista um elemento diferente dos demais, o Python irá tipar o ARRAY pelo elemento mais específico

c = numpy.array([2, 98, -14, 7.8, 9, -70])

c.dtype

dtype('float64')

In [8]:
# Pode-se também ter um tipo STRING

d = numpy.array(['Machine Learning', 'Python', 'R', 'Hadoop', 'Spark', 'MongoDB'])

In [9]:
d.dtype

dtype('<U16')

In [11]:
# ARRAY do tipo Booleano

e = numpy.array([False, False, True, False])

In [12]:
e.dtype

dtype('bool')

# CAST de ARRAY

In [13]:
f = numpy.array([-8, -5, -17, 55.9, 0.1])

f.dtype

dtype('float64')

In [14]:
# É possível realizar um CAST com a função ASTYPE()

f.astype(int)

array([ -8,  -5, -17,  55,   0])

# Criando ARRAYS com operações aritméticas em tempo de execução

In [15]:
# A função ARANGE server para criar ARRAY

array = numpy.arange(0, 6)

In [16]:
array

array([0, 1, 2, 3, 4, 5])

In [17]:
# Pode-se criar o array com qualquer operação aritmética

array = numpy.arange(0, 11) * 4

In [18]:
array

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [19]:
# Potenciação

array = numpy.arange(24) ** 3

In [20]:
array

array([    0,     1,     8,    27,    64,   125,   216,   343,   512,
         729,  1000,  1331,  1728,  2197,  2744,  3375,  4096,  4913,
        5832,  6859,  8000,  9261, 10648, 12167], dtype=int32)

# Operações Aritméticas entre ARRAYS

In [21]:
arrayA = numpy.arange(0, 11)
arrayB = numpy.arange(0, 11) + 1

In [22]:
arrayA

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
# Soma

arrayA + arrayB

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [26]:
# Subtração

arrayA - arrayB

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [28]:
# Divisão

arrayA / arrayB

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ,
        0.83333333,  0.85714286,  0.875     ,  0.88888889,  0.9       ,
        0.90909091])

In [29]:
# Multiplicação

arrayA * arrayB

array([  0,   2,   6,  12,  20,  30,  42,  56,  72,  90, 110])

In [30]:
# Comparaçao de ARRAYS

arrayA == arrayB

array([False, False, False, False, False, False, False, False, False,
       False, False], dtype=bool)

In [31]:
arrayA > arrayB

array([False, False, False, False, False, False, False, False, False,
       False, False], dtype=bool)

In [33]:
arrayA < arrayB

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [ ]:
# Pode-se também utilizar a tabela verdade para comparar dois ARRAYS utilizando por exemplo o operador lógico AND

In [34]:
array1 = numpy.array([False, True, True, True])
array2 = numpy.array([False, True, False, True])

numpy.logical_and(array1, array2)

array([False,  True, False,  True], dtype=bool)

In [35]:
array1 = numpy.array([False, True, True, True])
array2 = numpy.array([False, True, False, True])

numpy.logical_or(array1, array2)

array([False,  True,  True,  True], dtype=bool)

# ARRAYS com tamanho diferente

In [36]:
A = numpy.array([1, 2, 3, 4, 5])
B = numpy.array([1, 2, 3])

In [37]:
A + B # Não é possível fazer operação com número de elementos diferentes

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [38]:
A * B # Não é possível fazer operação com número de elementos diferentes

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

# DOT Product

In [39]:
A = numpy.array([2, 4, 6, 8])
B = numpy.array([2, 2, 2, 2])

In [40]:
# HADMARD Product

A * B # Multiplicado índice por índice ( 2*2) (4*2) (6*2) (8*2) 

array([ 4,  8, 12, 16])

In [41]:
# DOT Product

print(numpy.dot(A, B)) # Efetuado a soma de todos os elementos ( 4+8+12+16) 

40


# CÓPIAS de ARRAYS

In [42]:
A = numpy.arange(10)

In [43]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
B = A[5 :]

In [45]:
B

array([5, 6, 7, 8, 9])

In [46]:
A[:] = 0 # Foi criado uma referência e não uma cópia

In [47]:
B

array([0, 0, 0, 0, 0])

In [48]:
A = numpy.arange(10)

In [49]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
B = A[5 :].copy()

In [51]:
B

array([5, 6, 7, 8, 9])

In [52]:
A[:] = 0

In [53]:
B

array([5, 6, 7, 8, 9])