In [1]:
import numpy

In [2]:
a = [2, 5, 9, 11, 17, 98, 100]

array = numpy.array(a)

print(type(array))

<class 'numpy.ndarray'>


In [3]:
# Verificando o tamanho do ARRAY

print(array.shape)

(7,)


In [4]:
# Primeiro elemento

array[0]

2

In [5]:
# Elemento do índice 2

array[2]

9

In [6]:
# Último elemento

array[-1]

100

In [7]:
# Trazendo do índice 1 até 5 (exclusivo)

print(array[1:5])

[ 5  9 11 17]


In [8]:
# Utilizando um passo de 2 em 2

print(array[1:5:2])

[ 5 11]


In [11]:
# Trazendo com índice negativo.
# -7 representa o primeiro da esquerda e o -3 o último elemento a ser trazido ( exclusivo)

print(array[-7 : -3])

[ 2  5  9 11]


In [12]:
# Índice 3 até o final

print(array[3 :])

[ 11  17  98 100]


In [13]:
# Início até o índice 4

print(array[: 4])

[ 2  5  9 11]


In [14]:
# Invertendo o ARRAY - Início até o final ao passo -1
# a = [2, 5, 9, 11, 17, 98, 100] ARRAY original

array[:: -1]

array([100,  98,  17,  11,   9,   5,   2])

In [15]:
# Copiando um ARRAY por referência

b = array[:]
print(b)

[  2   5   9  11  17  98 100]


In [16]:
# Concatenando 2 ARRAYS

x = numpy.array([1002, 49, 77, 999])
y = numpy.array([10, 987, 4000])

z = numpy.concatenate([x,y])

In [17]:
print(z)

[1002   49   77  999   10  987 4000]
