In [1]:
import numpy

# Operações com ARRAYS Multidimensionais

In [ ]:
# Lembrado que a notação é sempre LINHA(), COLUNA() 

In [3]:
A = [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

array = numpy.array(A)

print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
# Primeira linha

print(array[0])

[1 2 3 4]


In [5]:
# Linha de índice 1

print(array[2])

[ 9 10 11 12]


In [6]:
# Primeira linha e última coluna

print(array[0, -1])

4


In [7]:
# Atribuindo um valor a uma posição da matriz

array[0, 0] = 0

print(array)

[[ 0  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# Trabalhando com intervalos

In [8]:
# Obtendo os índices centrais

print(array[1:3, 1:3])

[[ 6  7]
 [10 11]]


In [9]:
# Obtendo o intervalo 7, 8, 11, 12

print(array[1:3, 2:4])

[[ 7  8]
 [11 12]]


In [10]:
# Obtendo somente a última coluna

print(array[:, -1])

[ 4  8 12 16]


In [11]:
# Obtendo somente a última linha

print(array[-1, :])

[13 14 15 16]


In [15]:
# Concatenando ARRAYS Multidimensionais

A = numpy.array([ [2, 4, 6], [9, 7, 5] ])
B = numpy.array([ [1, 3, 4]] )

C = numpy.concatenate((A, B))

In [16]:
print(C)

[[2 4 6]
 [9 7 5]
 [1 3 4]]
