In [ ]:
# Matrizes são objetos ESTRITAMENTE bidimensionais, o que torna mais fácil as operações aritméticas

In [1]:
import numpy

In [2]:
A = numpy.matrix([ [0, 1], [1, 0] ])
B = numpy.matrix([ [2, 3], [4, 5] ])

Z = numpy.array([
    [[2, 6], [8, 4]],
    [[2, 6], [8, 4]],
    [[2, 6], [8, 4]]
])

Y = numpy.array([2, 6, 8, 4])

In [3]:
Z = numpy.matrix([
    [[2, 6], [8, 4]],
    [[2, 6], [8, 4]],
    [[2, 6], [8, 4]]
])

# Não é possível criar matriz que não seja BI-dimensional

ValueError: matrix must be 2-dimensional

In [5]:
print(type(A))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [6]:
print(type(Z))

<class 'numpy.ndarray'>


In [7]:
print(type(Y))

<class 'numpy.ndarray'>


In [8]:
print(A) # BIDIMENSIONAL - Possui dois colchetes

[[0 1]
 [1 0]]


In [9]:
print(Z) # CUBO - Possui três ou mais colchetes

[[[2 6]
  [8 4]]

 [[2 6]
  [8 4]]

 [[2 6]
  [8 4]]]


In [10]:
print(Y) # UNIDIMENSIONAL - Possui apenas 1 colchete

[2 6 8 4]


In [11]:
A.shape # Possui duas dimensões, duas linhas e duas colunas

(2, 2)

In [12]:
Z.shape # Possui três dimensões, duas linhas e duas colunas

(3, 2, 2)

In [13]:
Y.shape # Unidimensional com 4 elementos em apenas 1 linha

(4,)

# SOMA

In [14]:
print( A + B) # Somado linha com linha e coluna com coluna 

[[2 4]
 [5 5]]


In [15]:
print( B + 3) # Somado 3 em cada valor da matriz B

[[5 6]
 [7 8]]


# SUBTRAÇÃO

In [16]:
print(A-B)

[[-2 -2]
 [-3 -5]]


# MULTIPLICAÇÃO

In [17]:
A = numpy.matrix([ [1, 2], [3, 4] ])

print(A)

[[1 2]
 [3 4]]


In [18]:
# Arrumação em 'CRUZ'

print(A * A)

[[ 7 10]
 [15 22]]


In [19]:
# Multiplicação índice a índice

print(numpy.multiply(A, A))

[[ 1  4]
 [ 9 16]]


# INVERSA

In [21]:
print(numpy.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [22]:
from numpy.linalg import inv

In [23]:
print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


# TRANSPOSTA ( pivô )

In [24]:
print(A.T)

[[1 3]
 [2 4]]
