# Transposição e Reshaping de ARRAYS

In [1]:
import numpy

In [2]:
A = numpy.array([ [100, 100,  100], [900, 900,900]])

In [3]:
A

array([[100, 100, 100],
       [900, 900, 900]])

In [4]:
A.T

array([[100, 900],
       [100, 900],
       [100, 900]])

In [5]:
numpy.transpose(A)

array([[100, 900],
       [100, 900],
       [100, 900]])

# BROADCASTING

In [6]:
B = numpy.array([ [200, 500, 800]])

In [7]:
B.T

array([[200],
       [500],
       [800]])

In [8]:
B.T + B

array([[ 400,  700, 1000],
       [ 700, 1000, 1300],
       [1000, 1300, 1600]])

# CONVERTENDO MATRIZ EM ARRAYS

In [12]:
A = numpy.array([ numpy.arange(1, 100, 15), numpy.arange(2, 100, 15) ])

In [13]:
A

array([[ 1, 16, 31, 46, 61, 76, 91],
       [ 2, 17, 32, 47, 62, 77, 92]])

In [14]:
A.shape

(2, 7)

In [15]:
A.ravel()

array([ 1, 16, 31, 46, 61, 76, 91,  2, 17, 32, 47, 62, 77, 92])

In [16]:
A.T.ravel()

array([ 1,  2, 16, 17, 31, 32, 46, 47, 61, 62, 76, 77, 91, 92])

# OPERADORES LÓGICOS

In [18]:
array = numpy.random.randint(1, 10, size = (4, 4))

In [19]:
array

array([[4, 2, 7, 9],
       [7, 5, 1, 8],
       [7, 7, 8, 1],
       [1, 3, 2, 4]])

In [20]:
numpy.any((array % 7 ) == 0)

True

In [21]:
numpy.all(array < 11)

True

# RESHAPING

In [22]:
array = numpy.arange(1, 16)

In [23]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
array.reshape(3, 5) # Para transformar em uma matriz, o número de linhas * colunas deve ser o valor totol do array 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# ORDENANDO O ARRAY

In [26]:
array = numpy.array([ [3, 2], [10, -1] ])

In [27]:
array

array([[ 3,  2],
       [10, -1]])

In [28]:
# Ordenando por linhas

array.sort(axis = 1) # axis 1 é para ordenar por linhas

In [29]:
array # Colocado em ordem crescente

array([[ 2,  3],
       [-1, 10]])

In [30]:
array = numpy.array([ [3, 2], [10, -1] ])

In [31]:
array

array([[ 3,  2],
       [10, -1]])

In [32]:
# Ordenando por colunas

array.sort(axis = 0) # axis 0 é para ordenar por colunas

In [33]:
array

array([[ 3, -1],
       [10,  2]])